---
  - hosts: all
    become: True
    roles: 
      - debian-security
    vars:
      debian_user: USER_NAME
      debian_version: DEBIAN_NAME
      debian_host: IP_OR_DOMAIN
      debian_private_key_file: ~/.ssh/SSH_PRIV_KEY
      debian_port: 22
      ansible_python_interpreter: /usr/bin/python3

# For Debian Kernel Version: $(uname -r)