- block:
  - name: ADD SOURCES FILE
    template:
      src: sources.list
      dest: /etc/apt/sources.list
      owner: "root"
      group: "root"
      mode: "0644"

  - name: ADD DEBIAN SOURCES
    template:
      src: debian.sources
      dest: /etc/apt/sources.list.d/
      owner: "root"
      group: "root"
      mode: "0644"

  - name: CUSTOM BASHRC
    template:
      src: bashrc
      dest: .bashrc
      owner: "{{ debian_user }}"
      group: "{{ debian_user }}"
      mode: "0644"

  - name: SPOTIFY
    deb822_repository:
      name: spotify
      types: deb
      uris: https://repository.spotify.com
      suites: stable
      signed_by: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
      enabled: true
      components:
        - non-free

  - name: TYPORA
    deb822_repository:
      name: typora
      types: deb
      uris: https://typora.io/linux
      suites: ./
      signed_by: https://typora.io/linux/public-key.asc
      enabled: true

  - name: VSCODE
    deb822_repository:
      name: vscode
      types: deb
      uris: https://packages.microsoft.com/repos/code
      suites: stable
      signed_by: https://packages.microsoft.com/keys/microsoft.asc
      enabled: true
      architectures:
        - amd64
      components:
        - main

  - name: NODEJS
    deb822_repository:
      name: nodejs
      types: deb
      uris: https://deb.nodesource.com/node_18.x
      suites: "{{ debian_version }}"
      signed_by: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      enabled: true
      components:
        - main

  - name: YARN
    deb822_repository:
      name: yarn
      types: deb
      uris: https://dl.yarnpkg.com/debian
      suites: stable
      signed_by: https://dl.yarnpkg.com/debian/pubkey.gpg
      enabled: true
      components:
        - main

  - name: DOCKER-CE
    deb822_repository:
      name: docker
      types: deb
      uris: https://download.docker.com/linux/debian
      suites: "{{ debian_version }}"
      signed_by: https://download.docker.com/linux/debian/gpg
      enabled: true
      architectures:
        - amd64
      components:
        - stable

  - name: VIRTUALBOX
    deb822_repository:
      name: virtualbox
      types: deb
      uris: https://download.virtualbox.org/virtualbox/debian
      suites: "{{ debian_version }}"
      signed_by: https://www.virtualbox.org/download/oracle_vbox_2016.asc
      enabled: true
      architectures:
        - amd64
      components:
        - contrib

  - name: KUBERNETES
    deb822_repository:
      name: kubernetes
      types: deb
      uris: https://pkgs.k8s.io/core:/stable:/v1.30/deb/ 
      suites: /
      signed_by: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
      enabled: true

  - name: HASHICORP
    deb822_repository:
      name: hashicorp
      types: deb
      uris: https://apt.releases.hashicorp.com
      suites: "{{ debian_version }}"
      signed_by: https://apt.releases.hashicorp.com/gpg
      enabled: true
      architectures:
        - amd64
      components:
        - main

  - name: AZURE-CLI
    deb822_repository:
      name: azure-cli
      types: deb
      uris: https://packages.microsoft.com/repos/azure-cli
      suites: "{{ debian_version }}"
      signed_by: https://packages.microsoft.com/keys/microsoft.asc
      enabled: true
      architectures:
        - amd64
      components:
        - main

  - name: BRAVE-BROWSER
    deb822_repository:
      name: brave-browser
      types: deb
      uris: https://brave-browser-apt-release.s3.brave.com
      suites: stable
      signed_by: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
      enabled: true
      components:
        - main

  - name: UPDATE CACHE
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: UPGRADE ALL PACKAGES
    apt:
      name: "*"
      state: latest

  - name: INSTALL PACKAGES BASICS
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - wget
        - gnupg
        - gnupg-agent
        - lsb-release
        - vim
        - build-essential
        - checkinstall
        - make
        - automake
        - autoconf
        - dkms
        - git
        - dirmngr
        - software-properties-common
      state: latest

  - name: UNINSTALL DEFAULT PACKAGES
    apt:
      name:
        - vim-tiny
        - xsane
        - xsane-common
        - exfalso
        - parole
        - xterm
      state: absent

  - name: UNINSTALL UNNECESSARY PACKAGES
    apt:
      autoremove: yes

