- block:
  - name: ADD SOURCES FILE
    template:
      src: sources.list
      dest: /etc/apt/sources.list
      owner: "root"
      group: "root"
      mode: "0644"

  - name: ADD DEBIAN SOURCES
    template:
      src: debian.sources
      dest: /etc/apt/sources.list.d/
      owner: "root"
      group: "root"
      mode: "0644"

  - name: CUSTOM BASHRC
    template:
      src: bashrc
      dest: .bashrc
      owner: "{{ debian_user }}"
      group: "{{ debian_user }}"
      mode: "0644"

  - name: SPOTIFY GPG
    apt_key:
      url: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
      state: present

  - name: SPOTIFY
    deb822_repository:
      name: spotify
      types: deb
      uris: https://repository.spotify.com
      suites: stable
      components:
        - non-free

#  - name: TYPORA KEY
#    apt_key:
#      url: https://typora.io/linux/public-key.asc
#      state: present
#
#  - name: TYPORA
#    apt_repository:
#      repo: deb https://typora.io/linux ./
#      filename: typora
#      state: present
#
#  - name: VSCODE KEY
#    apt_key:
#      url: https://packages.microsoft.com/keys/microsoft.asc
#      state: present
#
#  - name: VSCODE
#    apt_repository:
#      repo: deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
#      filename: vscode
#      state: present
#
#  - name: NODEJS KEY
#    apt_key:
#      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
#      keyring: /usr/share/keyrings/nodesource.gpg
#      state: present
#
#  - name: NODEJS
#    apt_repository:
#      repo: deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x {{ debian_version }} main
#      filename: nodesource
#      state: present
#
#  - name: NODEJS SRC
#    apt_repository:
#      repo: deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_16.x {{ debian_version }} main
#      filename: nodesource
#      state: present
#
#  - name: YARN KEY
#    apt_key:
#      url: https://dl.yarnpkg.com/debian/pubkey.gpg
#      keyring: /usr/share/keyrings/yarnkey.gpg
#      state: present
#
#  - name: YARN
#    apt_repository:
#      repo: deb [signed-by=/usr/share/keyrings/yarnkey.gpg] https://dl.yarnpkg.com/debian stable main
#      filename: yarn
#      state: present
#
#  - name: DOCKER GPG
#    apt_key:
#      url: https://download.docker.com/linux/debian/gpg
#      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
#      state: present
#
#  - name: DOCKER CE
#    apt_repository:
#      repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian {{ debian_version }} stable
#      filename: docker-ce
#      state: present
#
#  - name: VIRTUALBOX KEY
#    apt_key:
#      url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
#      state: present
#
#  - name: VIRTUALBOX
#    apt_repository:
#      repo: deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ debian_version }} contrib
#      filename: virtualbox
#      state: present
#
#  - name: KUBECTL KEY
#    apt_key:
#      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
#      keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
#      state: present  
#
#  - name: KUBECTL
#    apt_repository:
#      repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
#      filename: kubectl
#      state: present
#
#  - name: TERRAFORM KEY
#    apt_key:
#      url: https://apt.releases.hashicorp.com/gpg
#      state: present
#
#  - name: TERRAFORM
#    apt_repository:
#      repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ debian_version }} main
#      filename: hashicorp
#      state: present
#
#  - name: AZURE-CLI KEY
#    apt_key:
#      url: https://packages.microsoft.com/keys/microsoft.asc
#      keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
#      state: present
#
#  - name: AZURE-CLI
#    apt_repository:
#      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ debian_version }} main
#      filename: azure-cli
#      state: present
#
#  - name: BRAVE BROWSER KEY
#    apt_key:
#      url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
#      keyring: /usr/share/keyrings/brave-browser-archive-keyring.gpg
#      state: present
#
#  - name: BRAVE BROWSER
#    apt_repository:
#      url: deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
#      filename: brave-browser
#      state: present      
#
#  - name: UPDATE CACHE
#    apt:
#      update_cache: yes
#      cache_valid_time: 3600
#
#  - name: UPGRADE ALL PACKAGES
#    apt:
#      name: "*"
#      state: latest
#
#  - name: INSTALL PACKAGES BASICS
#    apt:
#      name:
#        - apt-transport-https
#        - ca-certificates
#        - curl
#        - gnupg
#        - gnupg-agent
#        - lsb-release
#        - vim
#        - build-essential
#        - checkinstall
#        - make
#        - automake
#        - autoconf
#        - dkms
#        - git
#        - dirmngr
#        - software-properties-common
#      state: latest
#
#  - name: UNINSTALL DEFAULT PACKAGES
#    apt:
#      name:
#        - vim-tiny
#        - xsane
#        - xsane-common
#        - exfalso
#        - parole
#        - xterm
#      state: absent
#
#  - name: UNINSTALL UNNECESSARY PACKAGES
#    apt:
#      autoremove: yes

